version: '2.1'
services:
    webserver:
        image: 146006631841.dkr.ecr.us-west-1.amazonaws.com/docker-airflow:1.0.13
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=kW71__YwaYMUkCTxvDrUQG2K85qfGO-R9lxseMC1diU=
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./src:/usr/local/airflow/src
            - ./node_modules:/usr/local/airflow/node_modules
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
